alias ..='cd ..'
alias e='vim'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -al'
alias atom='atom .'
alias grep='grep --color=auto'
alias view='/usr/share/vim/vim81/macros/less.sh'
alias vi='vim'
alias kilburn='ssh d75307sc@kilburn.cs.man.ac.uk'
alias pi='ssh pi@192.168.1.217'
alias spotify='flatpak run com.spotify.Client'
alias discord='flatpak run com.discordapp.Discord'
alias duckgame='.steam/steam/steamapps/common/DuckGame/DuckGame.sh'
alias kilburnMount='sshfs d75307sc@kilburn.cs.man.ac.uk:/home/d75307sc ~/kilburn'
alias kilburnUnmount='fusermount3 -u ~/kilburn'
